name: Called Workflow
on:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.greeting }}

  test2:
    runs-on: ubuntu-latest
    environment: env1
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/test
      with:
        who-to-greet: 'Mona the Octocat'
