name: Caller Workflow
on: [workflow_dispatch, push]
jobs:
  #upload:
    #runs-on: ubuntu-latest
    #steps:
      #- run: echo hello > /tmp/world.txt

      #- uses: actions/upload-artifact@v3
        #with:
          #name: my-artifact
          #path: /tmp/world.txt
  test:
    uses: ./.github/workflows/called.yaml
    with:
      greeting: bye
