name: 'test'
"on":
  workflow_dispatch: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: env1
    steps:
      - run: echo XXX1 ${{ secrets.ENV_SECRET }}
      - run: echo XXX2 ${{ secrets.REPO_SECRET }}
